def find_substring(s, t):
    """Find all locations of t as a substring of s."""
    locations = []
    start = 0
    while True:
        index = s.find(t, start)
        if index == -1:
            break
        locations.append(index + 1)
        start = index + 1
    return locations
s = "CACGATTATACCGATTATCCGCCGATTATCGATTATTAACGATTATAACACAGACGATTATGGCGCGATTATCGATTATGACGATTATCTTAACTACACGATTATGTCCGATTATCGATTATGACCGATTATCGATTATGGGAGTCGATTATCTCGATTATCGATTATCTACGATTATTGCGATTATACGATTATCGATTATCAACCGATTATCGATTATCACGATTATCGATTATCCGATTATCCGCGATTATGCGATTATACGATTATCTCGATTATTCGATTATCGATTATGGTTTCTTGCCGATTATCGATTATGTCGATTATCTATAACGATTATTCAATAACATACGATTATAGCGATTATGCGATTATCGATTATACAGAAAAACGATTATAACTAGGTCGATTATTTAGTTAGGGCATCGATTATCGATTATCGATTATCCCGATTATCGATTATTGGGCGATTATCGATTATAACCGATTATGCGATTATCTGATACAGGTCGCGGACGATTATCGATTATACCGATTATGGCGATTATACGATTATCGATTATGTCGATTATGCGATTATCAGACGATTATACGATTATAATCCGTCGGCGATTATTTACGATTATTCGATTATAACCGATTATCGATTATTCCGATTATCGATTATAACGATTATCGATTATCGATTATCGATTATTGGTCGAGCGATTATATCGATTATTGAGTCGATTATCGATTATCGATTATGACGATTATGGAGTCGATTATCGAGGCGGCCGATTATCTGCGATTATCAACGATTATCGATTATAAACGATTATTTTTGCCGATTATCGATTATTGCGATTATTTCGATTATATCGATTATGGACGATTATTATGCGATTATCCGATTATCCCGATTATAGTCGATTATGCGCGATTATCGATTATGAGGCAGCTACCCGATTATCTTCGTTT"
t = "CGATTATCG"

locations = find_substring(s, t)
print(" ".join(map(str, locations)))  # Output: 2 4 10
